version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Root Monorepo
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Maintain dependencies for apps/client
  - package-ecosystem: "npm"
    directory: "/apps/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain dependencies for apps/server
  - package-ecosystem: "npm"
    directory: "/apps/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
